services:
  postgres:
    image: postgres:16-alpine
    container_name: fitness-hw5-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '15432:5432'
    volumes:
      - fitness_hw5_postgres_data:/var/lib/postgresql/data
      - ./db/init-multiple-databases.sh:/docker-entrypoint-initdb.d/01-init-multiple-databases.sh:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 20

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: fitness-hw5-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: fitness
      RABBITMQ_DEFAULT_PASS: fitness
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - fitness_hw5_rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  fitness_hw5_postgres_data:
  fitness_hw5_rabbitmq_data:
